# Generated by Django 2.2 on 2020-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("authors", models.ManyToManyField(to="test1.Author")),
            ],
        ),
    ]
